### PR TITLE
exit grain process if 'save' returned with no provider

### LINKED ISSUE #12: grain init crashes when grain ref has no provider
verify_etag

erlans_grain (236) calls:
```erl
             {CbState2, ETag1} = verify_etag(CbModule, Id, Provider, ETag, CbState1),
```
if the grain either has no `provider` the variable `Provider` is bound to undefined, however verify_etag calls `Provider:...()` even if no provider is provided.

### PR DESCRIPTION
**Pull request by tsloughter**
Resolves #12 

A grain is not required to have a storage provider. If it wants to use the default provider it must return `default_provider` from the callback. Otherwise it is assumed it does not want to persist state through `erleans_grain` and either has no state it wants to save or will do it on its own.

### CODE REVIEW

File: src/erleans.erl [hunk 1]
```diff
@@ -73,12 +73,28 @@ get_stream(StreamProvider, Topic, SequenceToken) ->
...
+        undefined ->
+            undefined;
+        Name ->
+            find_provider_config(Name)
+    end.
+
+-spec find_provider_config(atom()) -> provider().
+find_provider_config(default) ->
+    %% throw an exception if default_provider is set to default, which would cause an infinite loop
+    erleans_config:get(default_provider) =/= default orelse throw(bad_default_provider_config),
```
Comment (evanmcc) [inline src/erleans.erl]: make this into a case so that `erleans_config:get(default_provider)` is only called once?
